# This is a basic workflow to help you get started with Actions

name: CI Pro-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Create user
        run: |
          sudo -u postgres psql -c "CREATE USER test_user WITH PASSWORD 'test_password'"
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          PRO_SANG_SERVER_DATABASE: postgres
          PRO_SANG_SERVER_DATABASE_PASSWORD: test_password
          PRO_SANG_SERVER_DATABASE_USERNAME: test_user
          PRO_SANG_SERVER_DB_PORT: 5432
          PRO_SANG_SERVER_DB_URL: localhost
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pro-sang-server:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pro-sang-server:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pro-sang-server:buildcache,mode=max
       
