# This is a basic workflow to help you get started with Actions

name: CD Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Test and Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          PRO_SANG_SERVER_DATABASE: ${{secrets.PRO_SANG_SERVER_DATABASE}}
          PRO_SANG_SERVER_DATABASE_PASSWORD: ${{secrets.PRO_SANG_SERVER_DATABASE_PASSWORD}}
          PRO_SANG_SERVER_DATABASE_USERNAME: ${{secrets.PRO_SANG_SERVER_DATABASE_USERNAME}}
          PRO_SANG_SERVER_DB_PORT: ${{secrets.PRO_SANG_SERVER_DB_PORT}}
          PRO_SANG_SERVER_DB_URL: ${{secrets.PRO_SANG_SERVER_DB_URL}}
       
