name: CI Pro-Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI Pro-Build"]
    branches: [main]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Docker Deploy
        run: |
          chmod +x ./.github/bin/deploy.sh
          ./.github/bin/deploy.sh
        shell: bash
        env:
           PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
           KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
           HOST: ${{secrets.SSH_HOST}}
           DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
           DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
           ENVS: ${{secrets.ENVIROMENTS_FILE}}
           USER: ${{secrets.USER}}
